# Generated by Django 5.0.2 on 2024-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('div', models.CharField(max_length=10)),
                ('code', models.IntegerField(max_length=3)),
                ('about', models.TextField()),
            ],
        ),
    ]
