# Generated by Django 5.0.2 on 2024-06-10 13:00

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4_modelmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('modelManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
