# Generated by Django 5.0.2 on 2024-06-10 13:22

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_modelmanager', '0002_alter_student_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
            managers=[
                ('teachers', django.db.models.manager.Manager()),
            ],
        ),
    ]
