# Generated by Django 5.0.2 on 2024-06-12 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_examples', '0002_rename_pblish_in_post_publish_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4_examples.page'),
        ),
    ]
