# Generated by Django 6.0.4 on 2026-08-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericcbv', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
