# Generated by Django 5.0.2 on 2024-06-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_relation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExacCenter',
            new_name='ExamCenter',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='examcenter_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app2_relation.examcenter'),
            preserve_default=False,
        ),
    ]
