# Generated by Django 5.0.2 on 2024-06-11 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_onetoone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='husband',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app1_onetoone.husband'),
        ),
    ]
