# Generated by Django 5.0.2 on 2024-06-11 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_onetoone', '0002_alter_wife_husband'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='husband',
            field=models.OneToOneField(limit_choices_to={'salary': 5000}, on_delete=django.db.models.deletion.CASCADE, to='app1_onetoone.husband'),
        ),
    ]
