# Generated by Django 5.0.2 on 2024-06-11 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_onetoone', '0003_alter_wife_husband'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1_onetoone.usermodel')),
                ('publish', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('panna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1_onetoone.page')),
                ('likes', models.IntegerField()),
            ],
            bases=('app1_onetoone.page',),
        ),
    ]
