# Generated by Django 5.0.2 on 2024-03-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
