# Generated by Django 5.0.2 on 2024-03-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='div',
            new_name='division',
        ),
    ]
