# Generated by Django 5.0.2 on 2024-03-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_subject_rename_div_student_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
