# Generated by Django 6.0.4 on 2026-07-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudwithfbv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
